clone_folder: c:\gopath\src\github.com\contribsys\faktory_worker_go

environment:
  GOPATH: c:\gopath

install:
  - echo %PATH%
  - echo %GOPATH%
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - go version
  - go env

before_build:
  - go get -u github.com/contribsys/faktory

build_script:
  - go build test/main.go

test_script:
  - go test
