clone_folder: c:\gopath\src\github.com\contribsys\faktory_worker_go

environment:
  GOPATH: c:\gopath

install:
  - echo %PATH%
  - echo %GOPATH%
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - go version
  - go env

build: false

test_script:
  - go get -d -u github.com/contribsys/faktory
  - go build test/main.go
  - go test
